"""Permission policy tables used by the Perfil component and UI."""

PAGINAS: list[tuple[str, str]] = [
    ("veiculos", "Veículos"),
    ("investidores", "Investidores"),
    ("clientes", "Clientes"),
    ("compras", "Compras"),
    ("consignacoes", "Consignações"),
    ("custos-veiculos", "Custos"),
    ("vendas", "Vendas"),
]
PAGINAS_VALIDAS = {chave for chave, _ in PAGINAS}
ROTAS_DERIVADAS = {"fechamentos-vendas": "vendas", "rsd": "veiculos"}

# Campos sensíveis e operações que podem ser restringidos por perfil, por página.
CAMPOS_PROTEGIDOS: dict[str, list[tuple[str, str]]] = {
    "veiculos": [
        ("modelo", "Modelo"),
        ("marca", "Marca"),
        ("placa", "Placa"),
        ("chassi", "Chassi"),
        ("renavam", "RENAVAM"),
        ("tipo", "Tipo"),
        ("ano", "Ano"),
        ("km", "KM"),
        ("status", "Estado"),
        ("preco", "Preço Anunciado"),
        ("custo", "Preço de Custo"),
        ("tipo_entrada", "Tipo de Entrada"),
        ("investidor", "Investidor"),
        ("procuracao", "Procurador"),
        ("proprietario_registrado", "Proprietário Registrado"),
        ("revisao", "Revisão"),
        ("debitos", "Débitos"),
        ("tempo_estoque", "Tempo de Estoque"),
    ],
    "compras": [
        ("data_compra", "Data da Compra"),
        ("cliente", "Cliente"),
        ("documento_cliente", "Documento do Cliente"),
        ("status", "Estado"),
        ("placa", "Placa"),
        ("veiculo", "Veículo"),
        ("valor_compra", "Valor da Compra"),
        ("debitos", "Débitos"),
        ("observacoes", "Observações"),
        ("usuario", "Usuário"),
    ],
    "consignacoes": [
        ("data_consignacao", "Data da Consignação"),
        ("proprietario", "Proprietário"),
        ("documento_proprietario", "Documento do Proprietário"),
        ("status", "Estado"),
        ("placa", "Placa"),
        ("veiculo", "Veículo"),
        ("valor_venda", "Valor de Venda"),
        ("comissao_percentual", "Comissão (%)"),
        ("data_vencimento", "Data de Vencimento"),
        ("observacoes", "Observações"),
        ("usuario", "Usuário"),
    ],
    "custos-veiculos": [("valor", "Valor")],
    "vendas": [
        ("cliente", "Cliente"),
        ("veiculo", "Veículo"),
        ("data_venda", "Data da Venda"),
        ("valor_venda", "Valor da Venda"),
        ("valor_entrada", "Entrada"),
        ("debitos", "Débitos"),
        ("km", "KM"),
        ("veiculo_troca", "Veículo da Troca"),
        ("valor_diferenca", "Valor da Diferença"),
        ("pagamento_pendente", "Pagamento Pendente"),
        ("valor_pendente", "Valor Pendente"),
        ("datas_pagamento", "Datas de Pagamento"),
        ("forma_pagamento", "Forma de Pagamento"),
        ("parcelas", "Parcelas"),
        ("status", "Status"),
        ("observacoes", "Observações"),
        ("vendedor", "Usuário"),
        ("lucro", "Lucro Líquido (fechamento)"),
        ("participacao", "Participação por Investidor (fechamento)"),
    ],
}

CAMPOS_FORM_PROTEGIDOS: dict[str, dict[str, str]] = {
    "veiculos": {
        "modelo": "modelo",
        "marca": "marca",
        "placa": "placa",
        "chassi": "chassi",
        "renavam": "renavam",
        "tipo": "tipo",
        "ano": "ano",
        "km": "km",
        "status": "status",
        "preco": "preco",
        "tipo_entrada": "tipo_entrada",
        "investidor": "investidor_id",
        "procuracao": "procuracao",
        "proprietario_registrado": "proprietario_registrado",
        "revisao": "revisao",
        "debitos": "debitos",
    },
    "compras": {
        "data_compra": "data_compra",
        "cliente": "cliente_id",
        "status": "status",
        "veiculo": "veiculo_id",
        "valor_compra": "valor_compra",
        "debitos": "debitos",
        "observacoes": "observacoes",
    },
    "consignacoes": {
        "data_consignacao": "data_consignacao",
        "proprietario": "cliente_id",
        "status": "status",
        "veiculo": "veiculo_id",
        "valor_venda": "valor_venda",
        "comissao_percentual": "comissao_percentual",
        "data_vencimento": "data_vencimento",
        "observacoes": "observacoes",
    },
    "custos-veiculos": {"valor": "valor"},
    "vendas": {
        "cliente": "cliente_id",
        "veiculo": "veiculo_id",
        "data_venda": "data_venda",
        "valor_venda": "valor_venda",
        "valor_entrada": "valor_entrada",
        "debitos": "debitos",
        "km": "km",
        "veiculo_troca": "veiculo_troca_id",
        "valor_diferenca": "valor_diferenca",
        "pagamento_pendente": "pagamento_pendente",
        "valor_pendente": "valor_pendente",
        "datas_pagamento": "datas_pagamento",
        "forma_pagamento": "forma_pagamento",
        "parcelas": "parcelas",
        "status": "status",
        "observacoes": "observacoes",
        "vendedor": "vendedor_id",
    },
}

OPERACOES: dict[str, list[tuple[str, str]]] = {
    "veiculos": [
        ("editar", "Editar"),
        ("excluir", "Excluir"),
        ("abrir_cliente_vendedor", "Abrir cliente vendedor"),
        ("upload_documento", "Upload de documento do veículo"),
        ("abrir_imagens", "Abrir imagens do veículo"),
        ("enviar_imagens", "Enviar imagens"),
        ("excluir_imagens", "Excluir imagens"),
        ("abrir_procuracao", "Abrir procuração"),
        ("enviar_procuracao", "Enviar documentos de procuração"),
        ("excluir_procuracao", "Excluir documentos de procuração"),
    ],
    "investidores": [("editar", "Editar"), ("excluir", "Excluir")],
    "clientes": [
        ("cadastrar", "Cadastrar"),
        ("editar", "Editar"),
        ("excluir", "Excluir"),
        ("excluir_documento", "Excluir documento"),
    ],
    "compras": [
        ("cadastrar", "Cadastrar"),
        ("editar", "Editar"),
        ("excluir", "Excluir"),
        ("abrir_comprovante", "Abrir comprovantes"),
        ("enviar_comprovante", "Enviar comprovantes"),
        ("excluir_comprovante", "Excluir comprovante"),
    ],
    "consignacoes": [
        ("cadastrar", "Cadastrar"),
        ("editar", "Editar"),
        ("excluir", "Excluir"),
        ("abrir_contrato", "Abrir contratos"),
        ("enviar_contrato", "Enviar contratos"),
        ("excluir_contrato", "Excluir contrato"),
    ],
    "custos-veiculos": [("editar", "Editar"), ("excluir", "Excluir")],
    "vendas": [
        ("cadastrar", "Cadastrar"),
        ("editar", "Editar"),
        ("excluir", "Excluir"),
        ("baixar_contrato", "Baixar contrato"),
        ("fechar", "Fechar venda"),
        ("ver_fechamento", "Ver fechamento"),
    ],
}
