import os

import pytest
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from sqlalchemy import JSON

from tests.database import create_test_engine
from xtreme_system.database.core import Base


def _compare_server_default(
    _context: MigrationContext,
    _inspected_column: object,
    metadata_column: object,
    _rendered_inspected_default: str | None,
    _metadata_server_default: object,
    _rendered_metadata_default: str | None,
) -> bool | None:
    # PostgreSQL has no equality operator for the JSON type, so Alembic cannot
    # compare the '{}' default generated by the perfil migration.
    if isinstance(getattr(metadata_column, "type", None), JSON):
        return False
    return None


@pytest.mark.skipif(
    not os.environ.get("TEST_DATABASE_URL"),
    reason="migration drift check requires PostgreSQL",
)
def test_alembic_head_matches_sqlalchemy_metadata() -> None:
    engine = create_test_engine()
    try:
        with engine.connect() as connection:
            context = MigrationContext.configure(
                connection,
                opts={
                    "compare_server_default": _compare_server_default,
                    "compare_type": True,
                    "target_metadata": Base.metadata,
                },
            )

            assert compare_metadata(context, Base.metadata) == []
    finally:
        engine.dispose()
