"""auto_migration

Revision ID: 06e6490f892a
Revises: 1a8a10be7674
Create Date: 2026-07-20 03:08:32.276560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e6490f892a'
down_revision: Union[str, Sequence[str], None] = '1a8a10be7674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lancamento_caixa_investidor_id_fkey'), 'lancamento_investimento', type_='foreignkey', if_exists=True)
    op.create_foreign_key(None, 'lancamento_investimento', 'investidor', ['investidor_id'], ['id'])
    op.drop_constraint(op.f('veiculo_investidor_id_fkey'), 'veiculo', type_='foreignkey', if_exists=True)
    op.create_foreign_key(None, 'veiculo', 'investidor', ['investidor_id'], ['id'])
    op.drop_constraint(op.f('venda_veiculo_id_fkey'), 'venda', type_='foreignkey', if_exists=True)
    op.drop_constraint(op.f('venda_cliente_id_fkey'), 'venda', type_='foreignkey', if_exists=True)
    op.create_foreign_key(None, 'venda', 'veiculo', ['veiculo_id'], ['id'])
    op.create_foreign_key(None, 'venda', 'cliente', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venda', type_='foreignkey', if_exists=True)
    op.drop_constraint(None, 'venda', type_='foreignkey', if_exists=True)
    op.create_foreign_key(op.f('venda_cliente_id_fkey'), 'venda', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('venda_veiculo_id_fkey'), 'venda', 'veiculo', ['veiculo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'veiculo', type_='foreignkey', if_exists=True)
    op.create_foreign_key(op.f('veiculo_investidor_id_fkey'), 'veiculo', 'investidor', ['investidor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lancamento_investimento', type_='foreignkey', if_exists=True)
    op.create_foreign_key(op.f('lancamento_caixa_investidor_id_fkey'), 'lancamento_investimento', 'investidor', ['investidor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
