"""index fks veiculo

Revision ID: 5c6914b729c6
Revises: 74df76569f91
Create Date: 2026-07-07 21:46:42.522345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6914b729c6'
down_revision: Union[str, Sequence[str], None] = '74df76569f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_veiculo_investidor_id'), 'veiculo', ['investidor_id'], unique=False)
    op.create_index(op.f('ix_veiculo_meio_captacao_id'), 'veiculo', ['meio_captacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculo_meio_captacao_id'), table_name='veiculo')
    op.drop_index(op.f('ix_veiculo_investidor_id'), table_name='veiculo')
    # ### end Alembic commands ###
