"""initial schema

Revision ID: dff46eb8c6f9
Revises: 
Create Date: 2026-07-07 18:12:41.909072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff46eb8c6f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investidor_nome'), 'investidor', ['nome'], unique=True)
    op.create_table('meio_captacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meio_captacao_nome'), 'meio_captacao', ['nome'], unique=True)
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('moto', 'carro', name='tipoveiculo'), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('cor', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('procuracao', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('disponivel', 'vendido', name='statusveiculo'), nullable=False),
    sa.Column('investidor_id', sa.Integer(), nullable=False),
    sa.Column('meio_captacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investidor_id'], ['investidor.id'], ),
    sa.ForeignKeyConstraint(['meio_captacao_id'], ['meio_captacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculo_placa'), 'veiculo', ['placa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculo_placa'), table_name='veiculo')
    op.drop_table('veiculo')
    op.drop_index(op.f('ix_meio_captacao_nome'), table_name='meio_captacao')
    op.drop_table('meio_captacao')
    op.drop_index(op.f('ix_investidor_nome'), table_name='investidor')
    op.drop_table('investidor')
    # ### end Alembic commands ###
