"""add consignacao and imagem_contrato_consignacao tables

Revision ID: ebedcc4c5814
Revises: b8c9d0e1f2a3
Create Date: 2026-08-03 22:32:01.263777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebedcc4c5814'
down_revision: Union[str, Sequence[str], None] = 'b8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consignacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('data_consignacao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ativa', 'vendida', 'devolvida', 'cancelada', name='statusconsignacao'), server_default='ativa', nullable=False),
    sa.CheckConstraint('comissao_percentual IS NULL OR (comissao_percentual >= 0 AND comissao_percentual <= 100)', name='ck_consignacao_comissao_range'),
    sa.CheckConstraint('valor_venda > 0', name='ck_consignacao_valor_venda_positive'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consignacao_cliente_id'), 'consignacao', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_consignacao_idempotency_key'), 'consignacao', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_consignacao_usuario_id'), 'consignacao', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_consignacao_veiculo_id'), 'consignacao', ['veiculo_id'], unique=False)
    op.create_table('imagem_contrato_consignacao',
    sa.Column('consignacao_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['consignacao_id'], ['consignacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagem_contrato_consignacao_consignacao_id'), 'imagem_contrato_consignacao', ['consignacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imagem_contrato_consignacao_consignacao_id'), table_name='imagem_contrato_consignacao')
    op.drop_table('imagem_contrato_consignacao')
    op.drop_index(op.f('ix_consignacao_veiculo_id'), table_name='consignacao')
    op.drop_index(op.f('ix_consignacao_usuario_id'), table_name='consignacao')
    op.drop_index(op.f('ix_consignacao_idempotency_key'), table_name='consignacao')
    op.drop_index(op.f('ix_consignacao_cliente_id'), table_name='consignacao')
    op.drop_table('consignacao')
    # ### end Alembic commands ###
