[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[project]
name = "inventory_api"
version = "0.1.0"



requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy>=2.0",
    "alembic",
    "pydantic>=2",
    "pydantic-settings",
    "psycopg[binary]",
]

[tool.hatch.build.targets.wheel]
packages = ["xtreme_system"]

[tool.hatch.build.hooks.polylith-bricks]

[tool.polylith.bricks]
"../../components/xtreme_system/database" = "xtreme_system/database"
"../../components/xtreme_system/investidor" = "xtreme_system/investidor"
"../../components/xtreme_system/meio_captacao" = "xtreme_system/meio_captacao"
"../../components/xtreme_system/veiculo" = "xtreme_system/veiculo"
"../../bases/xtreme_system/api" = "xtreme_system/api"
