[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[project]
name = "inventory_api"
version = "0.1.0"



requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy>=2.0",
    "alembic",
    "pydantic>=2",
    "pydantic-settings",
    "psycopg[binary]",
    "pyjwt",
    "pwdlib[argon2]",
    "python-multipart",
    "jinja2",
]

[tool.hatch.build.targets.wheel]
packages = ["xtreme_system"]

[tool.hatch.build.hooks.polylith-bricks]

[tool.polylith.bricks]
"../../components/xtreme_system/auth" = "xtreme_system/auth"
"../../components/xtreme_system/usuario" = "xtreme_system/usuario"
"../../components/xtreme_system/database" = "xtreme_system/database"
"../../components/xtreme_system/caixa" = "xtreme_system/caixa"
"../../components/xtreme_system/investidor" = "xtreme_system/investidor"
"../../components/xtreme_system/meio_captacao" = "xtreme_system/meio_captacao"
"../../components/xtreme_system/veiculo" = "xtreme_system/veiculo"
"../../bases/xtreme_system/api" = "xtreme_system/api"
"../../components/xtreme_system/documento_veiculo" = "xtreme_system/documento_veiculo"
"../../components/xtreme_system/cliente" = "xtreme_system/cliente"
"../../components/xtreme_system/imagem_comprovante_compra" = "xtreme_system/imagem_comprovante_compra"
"../../components/xtreme_system/documento_contrato_venda" = "xtreme_system/documento_contrato_venda"
"../../components/xtreme_system/whatsapp" = "xtreme_system/whatsapp"
"../../components/xtreme_system/rsd" = "xtreme_system/rsd"
"../../components/xtreme_system/empresa" = "xtreme_system/empresa"
"../../components/xtreme_system/imagem_veiculo" = "xtreme_system/imagem_veiculo"
"../../components/xtreme_system/crud" = "xtreme_system/crud"
"../../components/xtreme_system/custo_veiculo" = "xtreme_system/custo_veiculo"
"../../components/xtreme_system/venda" = "xtreme_system/venda"
"../../components/xtreme_system/perfil" = "xtreme_system/perfil"
"../../components/xtreme_system/fechamento_venda" = "xtreme_system/fechamento_venda"
"../../components/xtreme_system/compra" = "xtreme_system/compra"
"../../components/xtreme_system/documento_procuracao" = "xtreme_system/documento_procuracao"
"../../components/xtreme_system/imagem_documento_cliente" = "xtreme_system/imagem_documento_cliente"
"../../components/xtreme_system/logging" = "xtreme_system/logging"
"../../components/xtreme_system/auditoria" = "xtreme_system/auditoria"
